version: 0.1

phases:
  build:
    commands:
      - npm install
      - npm run webpack

artifacts:
  files:
    - index.html
    - favico.ico
    - CV_for_DavidHay_05JAN2017_LATEST_ONLINE.pdf
    - styles/main.css
    - images/*
    - dist/bundle.js

