version: 0.1

phases:
  build:
    commands:
      - echo Nothing to do yet
artifacts:
  files:
    - index.html
    - favico.ico
    - CV_for_DavidHay_05JAN2017_LATEST_ONLINE.pdf
    - styles/main.css
    - images/*

